//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXGIS.TianDiTuThematicMaps.Web.AccurateGPSServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccurateGPSServiceRef.AccurateGPSSoap")]
    public interface AccurateGPSSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 AccurateResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Accurate", ReplyAction="*")]
        JXGIS.TianDiTuThematicMaps.Web.AccurateGPSServiceRef.AccurateResponse Accurate(JXGIS.TianDiTuThematicMaps.Web.AccurateGPSServiceRef.AccurateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Accurate", ReplyAction="*")]
        System.Threading.Tasks.Task<JXGIS.TianDiTuThematicMaps.Web.AccurateGPSServiceRef.AccurateResponse> AccurateAsync(JXGIS.TianDiTuThematicMaps.Web.AccurateGPSServiceRef.AccurateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccurateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Accurate", Namespace="http://tempuri.org/", Order=0)]
        public JXGIS.TianDiTuThematicMaps.Web.AccurateGPSServiceRef.AccurateRequestBody Body;
        
        public AccurateRequest() {
        }
        
        public AccurateRequest(JXGIS.TianDiTuThematicMaps.Web.AccurateGPSServiceRef.AccurateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccurateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal lat;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal lng;
        
        public AccurateRequestBody() {
        }
        
        public AccurateRequestBody(decimal lat, decimal lng) {
            this.lat = lat;
            this.lng = lng;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccurateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccurateResponse", Namespace="http://tempuri.org/", Order=0)]
        public JXGIS.TianDiTuThematicMaps.Web.AccurateGPSServiceRef.AccurateResponseBody Body;
        
        public AccurateResponse() {
        }
        
        public AccurateResponse(JXGIS.TianDiTuThematicMaps.Web.AccurateGPSServiceRef.AccurateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccurateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AccurateResult;
        
        public AccurateResponseBody() {
        }
        
        public AccurateResponseBody(string AccurateResult) {
            this.AccurateResult = AccurateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccurateGPSSoapChannel : JXGIS.TianDiTuThematicMaps.Web.AccurateGPSServiceRef.AccurateGPSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccurateGPSSoapClient : System.ServiceModel.ClientBase<JXGIS.TianDiTuThematicMaps.Web.AccurateGPSServiceRef.AccurateGPSSoap>, JXGIS.TianDiTuThematicMaps.Web.AccurateGPSServiceRef.AccurateGPSSoap {
        
        public AccurateGPSSoapClient() {
        }
        
        public AccurateGPSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccurateGPSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccurateGPSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccurateGPSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JXGIS.TianDiTuThematicMaps.Web.AccurateGPSServiceRef.AccurateResponse JXGIS.TianDiTuThematicMaps.Web.AccurateGPSServiceRef.AccurateGPSSoap.Accurate(JXGIS.TianDiTuThematicMaps.Web.AccurateGPSServiceRef.AccurateRequest request) {
            return base.Channel.Accurate(request);
        }
        
        public string Accurate(decimal lat, decimal lng) {
            JXGIS.TianDiTuThematicMaps.Web.AccurateGPSServiceRef.AccurateRequest inValue = new JXGIS.TianDiTuThematicMaps.Web.AccurateGPSServiceRef.AccurateRequest();
            inValue.Body = new JXGIS.TianDiTuThematicMaps.Web.AccurateGPSServiceRef.AccurateRequestBody();
            inValue.Body.lat = lat;
            inValue.Body.lng = lng;
            JXGIS.TianDiTuThematicMaps.Web.AccurateGPSServiceRef.AccurateResponse retVal = ((JXGIS.TianDiTuThematicMaps.Web.AccurateGPSServiceRef.AccurateGPSSoap)(this)).Accurate(inValue);
            return retVal.Body.AccurateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JXGIS.TianDiTuThematicMaps.Web.AccurateGPSServiceRef.AccurateResponse> JXGIS.TianDiTuThematicMaps.Web.AccurateGPSServiceRef.AccurateGPSSoap.AccurateAsync(JXGIS.TianDiTuThematicMaps.Web.AccurateGPSServiceRef.AccurateRequest request) {
            return base.Channel.AccurateAsync(request);
        }
        
        public System.Threading.Tasks.Task<JXGIS.TianDiTuThematicMaps.Web.AccurateGPSServiceRef.AccurateResponse> AccurateAsync(decimal lat, decimal lng) {
            JXGIS.TianDiTuThematicMaps.Web.AccurateGPSServiceRef.AccurateRequest inValue = new JXGIS.TianDiTuThematicMaps.Web.AccurateGPSServiceRef.AccurateRequest();
            inValue.Body = new JXGIS.TianDiTuThematicMaps.Web.AccurateGPSServiceRef.AccurateRequestBody();
            inValue.Body.lat = lat;
            inValue.Body.lng = lng;
            return ((JXGIS.TianDiTuThematicMaps.Web.AccurateGPSServiceRef.AccurateGPSSoap)(this)).AccurateAsync(inValue);
        }
    }
}
